/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminConnexionRouteImport } from './routes/admin-connexion'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MaReservationRouteImport } from './routes/ma-reservation'
import { Route as AuthenticatedGestionRouteImport } from './routes/_authenticated/gestion'
import { Route as AuthenticatedMonEspaceRouteImport } from './routes/_authenticated/mon-espace'
import { Route as VillasIndexRouteImport } from './routes/villas.index'
import { Route as VillasVillaIdRouteImport } from './routes/villas.$villaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnexionRoute = AdminConnexionRouteImport.update({
  id: '/admin-connexion',
  path: '/admin-connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MaReservationRoute = MaReservationRouteImport.update({
  id: '/ma-reservation',
  path: '/ma-reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGestionRoute = AuthenticatedGestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonEspaceRoute = AuthenticatedMonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VillasIndexRoute = VillasIndexRouteImport.update({
  id: '/villas/',
  path: '/villas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasVillaIdRoute = VillasVillaIdRouteImport.update({
  id: '/villas/$villaId',
  path: '/villas/$villaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-connexion': typeof AdminConnexionRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/inscription': typeof InscriptionRoute
  '/ma-reservation': typeof MaReservationRoute
  '/gestion': typeof AuthenticatedGestionRoute
  '/mon-espace': typeof AuthenticatedMonEspaceRoute
  '/villas/$villaId': typeof VillasVillaIdRoute
  '/villas/': typeof VillasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-connexion': typeof AdminConnexionRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/inscription': typeof InscriptionRoute
  '/ma-reservation': typeof MaReservationRoute
  '/gestion': typeof AuthenticatedGestionRoute
  '/mon-espace': typeof AuthenticatedMonEspaceRoute
  '/villas/$villaId': typeof VillasVillaIdRoute
  '/villas': typeof VillasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-connexion': typeof AdminConnexionRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/inscription': typeof InscriptionRoute
  '/ma-reservation': typeof MaReservationRoute
  '/_authenticated/gestion': typeof AuthenticatedGestionRoute
  '/_authenticated/mon-espace': typeof AuthenticatedMonEspaceRoute
  '/villas/$villaId': typeof VillasVillaIdRoute
  '/villas/': typeof VillasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-connexion'
    | '/comment-ca-marche'
    | '/inscription'
    | '/ma-reservation'
    | '/gestion'
    | '/mon-espace'
    | '/villas/$villaId'
    | '/villas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-connexion'
    | '/comment-ca-marche'
    | '/inscription'
    | '/ma-reservation'
    | '/gestion'
    | '/mon-espace'
    | '/villas/$villaId'
    | '/villas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-connexion'
    | '/comment-ca-marche'
    | '/inscription'
    | '/ma-reservation'
    | '/_authenticated/gestion'
    | '/_authenticated/mon-espace'
    | '/villas/$villaId'
    | '/villas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminConnexionRoute: typeof AdminConnexionRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  InscriptionRoute: typeof InscriptionRoute
  MaReservationRoute: typeof MaReservationRoute
  VillasVillaIdRoute: typeof VillasVillaIdRoute
  VillasIndexRoute: typeof VillasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-connexion': {
      id: '/admin-connexion'
      path: '/admin-connexion'
      fullPath: '/admin-connexion'
      preLoaderRoute: typeof AdminConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ma-reservation': {
      id: '/ma-reservation'
      path: '/ma-reservation'
      fullPath: '/ma-reservation'
      preLoaderRoute: typeof MaReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestion': {
      id: '/_authenticated/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof AuthenticatedGestionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-espace': {
      id: '/_authenticated/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof AuthenticatedMonEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/villas/': {
      id: '/villas/'
      path: '/villas'
      fullPath: '/villas/'
      preLoaderRoute: typeof VillasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/$villaId': {
      id: '/villas/$villaId'
      path: '/villas/$villaId'
      fullPath: '/villas/$villaId'
      preLoaderRoute: typeof VillasVillaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGestionRoute: typeof AuthenticatedGestionRoute
  AuthenticatedMonEspaceRoute: typeof AuthenticatedMonEspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGestionRoute: AuthenticatedGestionRoute,
  AuthenticatedMonEspaceRoute: AuthenticatedMonEspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminConnexionRoute: AdminConnexionRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  InscriptionRoute: InscriptionRoute,
  MaReservationRoute: MaReservationRoute,
  VillasVillaIdRoute: VillasVillaIdRoute,
  VillasIndexRoute: VillasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
